/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Lox {
    public static void main(String[] args) throws IOException {
        System.out.println(args.length);
        if (args.length > 1) {
            System.out.println("Usage: jlox [script]");
            System.exit(64); 
        } else if (args.length == 1) {
            runFile(args[0]);
        } else {
            runPrompt();
        }
    }

    public static void runFile(String s) {
        System.out.println("runFile()");
    }

    public static void runPrompt() {
        System.out.println("runPrompt()");
    }
}
